name: Build

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and cache node_modules
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Check types
        run: yarn check-types
        if: always()

      - name: Build
        run: yarn build
        if: always()

      - name: Lint
        run: yarn lint
        if: always()
